# Generated by Django 4.0.5 on 2022-06-10 16:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('url', models.URLField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('technologies', models.CharField(blank=True, max_length=200)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.TextField()),
                ('username', models.CharField(max_length=60)),
                ('profession', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profession')),
                ('location', models.CharField(blank=True, max_length=60)),
                ('contact', models.EmailField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created, ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('personal_website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Personal Website')),
                ('github_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='GitHub Link')),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram Link')),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn Link')),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter Link')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2200, verbose_name='Comment')),
                ('design_rating', models.IntegerField(default=0)),
                ('usability_rating', models.IntegerField(default=0)),
                ('content_rating', models.IntegerField(default=0)),
                ('avarage_rating', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.portfolio')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.profile', verbose_name='Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
