# Generated by Django 4.0.5 on 2022-06-12 14:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='caption',
            field=models.CharField(max_length=2200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(max_length=500, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='portfolio_image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_site_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Webiste Link'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='programming_language',
            field=models.CharField(max_length=500, null=True, verbose_name='Programming Language'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='repo_url',
            field=models.URLField(max_length=500, null=True, verbose_name='GitHub Repository'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
