# Generated by Django 4.0.5 on 2022-06-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_portfolio_date_remove_portfolio_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
