# Generated by Django 4.0.5 on 2022-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='average_creativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='average_design',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='average_usability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
