# Generated by Django 4.0.5 on 2022-06-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_portfolio_average_creativity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
    ]
